services:
  mongodb:
    image: mongo:8.0
    container_name: hintro-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - hintro_mongo_data:/data/db

volumes:
  hintro_mongo_data:
